### ISSUE TITLE
Feature 1: User can view the current Premier League Table

### ISSUE THREAD

**Issue by e-bales** [e-bales/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the Premier League table, showing all 20 teams' current position, badge, name, point total, win/loss/draw totals, and goals for/against/difference totals.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When visiting the webpage, the user will be able to see the current Premier League table with all usual information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/e-bales/ajax-project/assets/132625085/1a6c8757-2dcf-4df6-85c1-db246aff2463)
![image](https://github.com/e-bales/ajax-project/assets/132625085/1485cdb4-0308-46fd-8714-cbec41808ca2)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a header to match the figma.
- [x] Create the initial table elements, including the header with the column labels, and the blank footer.
   - [x] Add a few table entries to test how the rows line up with the columns.
- [x] With the basic table HTML set up, create a function generateTable() that takes an array of all the teams as an argument.
- [x] Create a function generateRow() that takes a single team object as an argument.
   - [x] this function should create the HTML for the team, and return that HTML.
- [x] Call generateRow() in generateTable() for each team in the array, and add the returned HTML to the table.
- [x] Submit API call to get table information for the Premier League.
   - [x] Save the response to the data object.
   - [x] Write a function that saves the data object to local storage, so we don't need to request the API call every time the user wants to see the table.
   - [x] Write a function the retrieves the local storage every time the user loads the web page.
   - [x] If it has been over 24 hours since we have requested the API for the table information, then call and save again. 
- [x] Pass in the API response to the generateTable() function to create the table and display to the user.
- [x] Add the color legend below the table.
- [x] Add CSS media query so the table expands in desktop view.
- [x] Create the CSS so the table matches the mock up.   
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
