### ISSUE TITLE
Feature 2: User can click on individual teams to see a team view.

### ISSUE THREAD

**Issue by e-bales** [e-bales/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view more information for individual teams, by clicking on the tame name in the table.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to explore different teams by clicking on a team name on the table, taking them to a new view with information about the team. Such information includes the distribution of goals scored home vs. away, goals conceded home vs. away, recent form, manager information, and most used formations.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/e-bales/ajax-project/assets/132625085/d41e6594-6b3f-4925-905d-e0dfb9f2cb17)
![image](https://github.com/e-bales/ajax-project/assets/132625085/16e7de2a-d3d5-470e-92dc-9c4718ea8af4)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the html of how the team-view page should look to match the wireframe.
  - [x] Include descriptive ID's for the elements for easy querySelectors.
  - [x] Add responsive CSS so the team-view page matches both the desktop and mobile wireframe's.
- [x] Remove the textContent but leave the HTML skeleton
- [x] Create a function, generateTeamView(), that takes a team ID as an argument, and replaces the correct text content and attribute values in the HTML skeleton.
  - [x] generateTeamView() will have to call the API with the team ID and use the response as basis for filling the text content. 
- [x] Add an event listener to the table that catches when a user clicks on a team in the table.
  - [x] Add a :hover pseudoclass to each table element that slightly highlights the row
  - [x] The event listener should set the table to hidden, and should remove the hidden class from team view.
  - [x] The event listener should also pass into generateTeamView() the team's ID that was clicked on.
- [x] Add an event listener to the league logo, that takes the user back to the league table by adding the hidden class to the team view and removing the hidden class from the table view.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
