### ISSUE TITLE
Feature 3: User can view the individual squad members for each team.

### ISSUE THREAD

**Issue by e-bales** [e-bales/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the individual squad members for each team, split up by position they play. They will see the players image, their number, and their name.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the Team View page, the user will see a button that they can click with text "View Squad". On clicking the button, the Team View page will disappear, and a new page displaying the team's players will appear. Each player will have their image shown, their number displayed, and their name displayed, as shown in the Figma.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/e-bales/ajax-project/assets/132625085/82f8ca8d-5e74-4ea4-9eba-66ec191c35b5)
![image](https://github.com/e-bales/ajax-project/assets/132625085/58f398bc-58e4-40f5-9517-cc2a7632d149)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Build a mock up in HTML to match the wireframe.
  - [x] Each player should be in its own individual div, so they are easy to replicate and add to the page depending on how many players in each position a team has.
  - [x] Have a 'goalkeepers', 'defenders', 'midfielders', and 'attackers' section, where players will be inserted.
  - [x] On mobile view, there should be two players per row, while on desktop, there should be four.
- [x] Create a function, generateSquad(), that takes the API response for requesting a squad.
  - [x] This function should loop through the different positions and pass player objects into the generatePlayer() function
  - [x] With the returned HTML element from generatePlayer(), append the element to the correct position.
- [x] Create a function, generatePlayer(), that takes player objects from the API response of requestion a team's squad.
  - [x] The function will create individual player subsections that match the wireframe.
  - [x] Each player subsection will include: player image, player number, player name.
  - [x] Return this player to be used in generateSquad()    
- [x] When the user clicks the 'View Squad" button, hide the team-view and show the squad-view
  - [x] Before switching views, send a request to the API for the squad of the currently viewed team.
  - [x] On successful return, call the function generateSquad(), and pass in the API response.
- [x] Update the nav-bar title to include 'squad' after the team name. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
