### ISSUE TITLE
Feature 4: User can view the league leaders for the Premier League

### ISSUE THREAD

**Issue by e-bales** [e-bales/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view who has scored the most goals and provided the most assists for the premier league. The top six players for each category will be shown.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click the "View Leaders" link in the header of the table view and the top goal scorers and playmakers will be shown. An image of the player, their name, and the club logo will be shown to identify the player. Additionally, the player's goals and assists tally, as well as either the player's goals per 90 minutes played for strikers, or total key passes for playmakers will be shown.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/e-bales/ajax-project/assets/132625085/9821222d-5a69-483c-8c81-eb514b0066b9)
![image](https://github.com/e-bales/ajax-project/assets/132625085/f78d30fb-6b06-4263-845c-2717fa019c69)

![image](https://github.com/e-bales/ajax-project/assets/132625085/9eb77596-ea2e-492a-92f9-9df28106d18b)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML and CSS to match the wireframes with dummy data.
  - [x] There should be three players shown per row in desktop-view, and 2 players per row shown in mobile-view. 
- [x] Create a function, generateLeagueLeaders, with two parameters, topScorers and topAssisters.
  - [x] The function should loop through the first six players from each API response, and generate a player card  to match the wireframe.
  - [x] These player cars will include their photo, their name, a team badge, and stats that correspond to their position.
  - [x] To generate a player card, pass the player object into generateLeader.
    - [x] Append the returned player element to either Top Goal Scorers or Top Playmakers.
- [x] Create generateLeader, that takes a player object and a boolean denoting if they are a scorer or assister.
  - [x] Create a player card to be returned to generateLeagueLeaders, where the difference between scorers or assisters is the final stat shown on the card.
  - [x] Create the appropriate HTML to match the wireframes, and return to generateLeagueLeaders.
- [x] User can click on the "View Leaders" option in the navbar.
  - [x] Clicking on the nav-bar should send an API request for the top scorers and playmakers, and on return, should pass the responses to generateLeagueLeaders() function.
  - [x] Additionally, after generateLeagueLeaders has been called, hide the league-view and show the leaders-view.
- [x] On return to the league-view, delete all players from the leader-view. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
