### ISSUE TITLE
Feature 5: User can view other leagues.

### ISSUE THREAD

**Issue by e-bales** [e-bales/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view other leagues besides the Premier League, such as the Bundesliga or Serie A.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click the caret next to the league name to open the dropdown of leagues, and can click on another league to swap view's to that league. The table will be shown, and all other functionality will be available. The user may click on team names to see the team view, and may see the league leaders or a team's squad. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/e-bales/ajax-project/assets/132625085/095c1412-eea1-4702-a0d6-9fd9e4fe0e7d)
![image](https://github.com/e-bales/ajax-project/assets/132625085/97e8fedc-d3ff-4565-bcbc-40e02d98c7ab)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When the user clicks the drop-down caret, a drop down appears with Europe's top five leagues as options.
- [x] Clicking on the current view should do nothing besides close the drop-down.
- [x] Clicking on another league should switch the table and the navbar to reflect the league clicked.
- [x] Create the HTML and CSS for the drop-down to match the wireframe.
  - [x] Each drop-down option should have their league id index as their value.
- [x] Add an event listener to the select element that hides the drop-down and attempts to load the new table.
  - [x] Check if the league table has previously been loaded this session with the data attribute.
    - [x] If it has, don't request the API and simply switch views.
  - [x] If the table hasn't been loaded, only request the API if the currently saved league table is null or over 24 hours old.
  - [x] On a needed API request, save the league data in data.leaguesArray and update the timer in data.timeAtUpdate.
  - [x] Then call generateBody with the API response.
- [x] Update the navbar to show the correct league logo and league title.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
